language: node_js
node_js:
- '8'
cache: yarn
script:
- yarn lint 
- yarn test
- ./ci-build.sh production
before_install:
- export TZ='Europe/London'
after_success:
- if [ $TRAVIS_BRANCH == 'spike/production-release' ]; then ./ci-deploy.sh production; fi;
env:
  global:
    secure: Ods8o8LHNW93m4hVgxeXceUsfOfIaSm758TutHR0B1gUtrTCUt7QpX2IUYQEe5hIS6P5uJPidJQbG06VPX3Gqw7bS2J22GVLPOyQsjPmF/HVTQARv406eqQj++lv8u3CeD24KGVoL6pwOzNpLNt7jxnYI5op6HaR2o855ebMMpg75oGg/Vt1JNewxBuXdlugtYGZ8nPsgcEnV/+LAfOBDtuSGvIr90mTeVaNETZw6ioUMZ3pt74A016fyYB5V2zW+4ER6xWnKZd02RXGC1nP5s8gj1ItnMB5NNSN6hX4TXB8ZghngWF/zn0XDK1SwWGtgemgGB1mujAFg/c2YqJC77C5efFVk3CDwzrhPGi8vveYvfKitQ5if7+HeZika68B0I62dYcfksgZE0MGCyVHgbpFrA1QGNatbfRdhz91StZ0KTYgPJ3A16UygRaQChaqGdspy5h7hn82orbhox/0uY/J3ocBJNl81w1pIHbQPnyLJr4Cui+LgUirY79NVc3jMMpJ9ZWB+/hC5dA0ZUGuehXbKblXqwBV2rAyy8c1lroiqUiVt/kxqZ6xlXFdwBeta3v17G8g1G+71W4ceOjsqBDpUqiS+V+EbJV0myhyCDO2z1FzkFNlG7BzsK8K5KTl7/6upOEDFIhHX4to0Zy12xGaiHyNLz9IHYkiQcPB7RY=
